date: "2014-10-01"
fake_today: 2014-09-30

raw_data_path: "data/extracted_data"

route: "MTA NYCT_M101"
next_stop_id: "MTA_402772"
inferred_date: "Weekday"
vehicle_id: 7600

two_segments: True
extension: '_twosegments'

network_date: '2014-10-03'

training_dates: ['2014-09-25','2014-09-26','2014-09-27','2014-09-28', '2014-09-29', '2014-09-30', '2014-10-01']


testing_dates: ['2014-10-02','2014-10-03']

previous_stop_list: ['MTA_400003', 'MTA_403148', 'MTA_400154', 'MTA_401666', 'MTA_401947', 'MTA_405151', 'MTA_403504']
stop_list: ['MTA_400007', 'MTA_403149', 'MTA_400157', 'MTA_401667', 'MTA_401948', 'MTA_405152', 'MTA_403505']

featureset:
  duration_history: ["duration_t_minus_10", "duration_t_minus_20", "duration_t_minus_30",
      "duration_t_minus_40", "duration_t_minus_50"]
  hour_breakdown: ["time_before_6", "time_6_9", "time_9_12", "time_12_16",
      "time_16_19", "time_19_24"]
  segments: ['sum_segment_duration', 'mean_segment_duration', 'number_segments', 'std_of_segments']




