date: "2014-09-30"
fake_today: 2014-09-30

raw_data_path: "data/extracted_data"

route: "MTA NYCT_M101"
next_stop_id: "MTA_402772"
inferred_date: "Weekday"
vehicle_id: 7600

two_segments: True
extension: '_twosegments'

network_date: '2014-09-30'